//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hasin.Taaghche.TaskScheduler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TaskSchedulerSetting.json")]
        public string SettingFileName {
            get {
                return ((string)(this["SettingFileName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("App_Data.installHangfireDatabase.sql")]
        public string HangfireDbScript {
            get {
                return ((string)(this["HangfireDbScript"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.mailgun.org")]
        public string SmtpUrl {
            get {
                return ((string)(this["SmtpUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int SmtpPort {
            get {
                return ((int)(this["SmtpPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("postmaster@taaghche.ir")]
        public string SmtpSenderMail {
            get {
                return ((string)(this["SmtpSenderMail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("142d2a3dccceb2e0b5fbab5a83b7bd5f")]
        public string SmtpSenderPassword {
            get {
                return ((string)(this["SmtpSenderPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAIAAAD2HxkiAAAAA3NCSVQICAjb4U/gAAAZeUlEQVR4nO2de" +
            "ZAcd3XH3+vuufbQyqtjd4W0uqzLEsH4jLGx8SFfGFMxuCBAJUUlQFGQilMhgaqkCKlK5aASCjChSHAAg" +
            "ylCArEEAcpgIHFIBZwCxYEYy5IlWVpp15a02p2de7r75Y85d3b26Jnu7d/07/txWbW7mu79STsf/d6v3" +
            "3u/H2//9MMEAAgPI+wBAKA7kBCAkIGEAIQMJAQgZCAhACEDCQEIGUi4DEKUd92s44Q9EBBZIOFS2CJpx" +
            "7lr0yvesXtP3nXDHg6IJlbYA1AUIbpk2wOx2FcO3nXnrt0XCoWPPffsNiPOYQ8MRA9I2IaC6046zp8ce" +
            "OUHb7k1ZZpEtD6ZJFfCHheIJpBwHo7I6XL5DaOjf3zja6/bvKX5t64bHp7MZCzGXAh8BhI2mHOcQSv2i" +
            "euu/u1rr+2zYi2/azJjKgRBAAmJiMoiE4XCu3ft+cBrbty1bl3b1/RbMREhzITAb3SX0BU579hXDq199" +
            "J57b9u+c4lXXr526OcXL8RXbWRAG7SWMO+6lmF85Kpr3vnqq9f39S3zaiGEoyAINJXQFjlTKt2+cePHb" +
            "7/zwMjISi5xBA6CQNBOQpdo2rY3p1KHb7vj/r37Vn7h1Rs2/uOJF/qDGxnQFb0kLLiuzfS+fVd88Kab1" +
            "yaTnq7FTAgCQhcJXZEp2755/fo/vemWG8bHO7gDloQgIKIvoRDN2naa+bM33fzOq67u+D6XJZIlTIYgA" +
            "CIuoS1yxrH/cO8Vv3fDjaMDA93cavPgYBESggCIsoSOyHAi+ZU7Dr5m6zYfUuwwEARDlFuZZhzn3Qdee" +
            "aMvBgIQGFGW0GJ6OZf1626GYaBmDQRBlCWMM5+Ym/PrbqlEcsSyEJIC34myhBbxqbm0X3djJsZMCAIgy" +
            "hIazGfz+bBHAcAyRFlCk/lEejbsUQCwDFGWkIiIOO/TRmlMHPm/LBAKUX9fMaeLRV/utLa/b0M87iJbC" +
            "Pwm+hKeuDTty51E4B8IhOhLaGO/UKA2EZcwxjw5i2czQGkiLyFlC75lKRCQgiCIuIQW8Vy+4Mutklasz" +
            "zRhIfCdiEsYZz6Xy/pizppEYhBlayAAIi6hyTRdLPrybEbQywSCIeoSEr9UyOMBKVCZqEvIfDqbLeN0Q" +
            "aAwEZeQifKOi6eaQGUiLqHJfDQ9a/sxE4oQ9lsDQRBxCYmIDH/KRwfi8X7LQu0o8B0NJGSezPjQX28Q9" +
            "SNPCAIg+hJabJz1Q0JCNAqCIfoSJohmCv4UzQAQBNGXMM485d92TwD4TvQlNJkzmAmBwkRfQoN5NpcLe" +
            "xQALEr0JTSJLpSKRV9ShXg0AwIg+hIyke2KL6cLDiZTKEIFvhN9CU3ms4X8RT8i0rWpPhwVCnwn+hIyU" +
            "cFxyo7d/a0QjoIgiL6EBtO0bedL5bAHAkB7oi8hEV8ol0s2JASKEn0JmajkuvlSKeyBANCe6EtIRAnmU" +
            "2nfjmcCwF+0kDDOPFNE0QxQFC0kxEwIVEYLCWPMZ1DDDVRFCwkNojk/HszE0dQLAkALCU3m4zOXur/P+" +
            "Nq1RUHhGvAZLSQkorIv+/+iZg0EgBYSMnNJ5ALOrwdKooeERDbJLLIUQEm0kJCIHKE5n87NBsBfdJGwJ" +
            "HIhkwl7FAC0QQsJmUiIcCwMUBMtJCSigutOo2gGKIkuEsaYC3709QLgO7pImGA+hco1oCS6SBgjmszlk" +
            "GsHCqKLhCbzdLHYZckLHAZBoJGEJzNzXR5sZjCjcA34ji4SGkRp2+7SoPHBNVlYCPxGGwmZX0jPSnepw" +
            "oRl+TUeAOroIiERERvdHtmLaRAEgFYS8lQ2G/YgAGhFLwnP5yAhUA6dJPRpkwsA/EUjCfuZX5pD+ShQD" +
            "o0kNJiLtg+nFALgLxpJGGeeujQd9igAaEUjCZmojBwDUA+NJLSYJ/O5gh/nZgPgIxpJaBBlynYZEgLF0" +
            "ElC5ulyqWijtReohU4SEs2USkX01wPF0EhCJpq1bRvhKFAMjSQ0mE8V8qUyzs0GaqGRhERErmDjQ6Aam" +
            "knI/CI2PgSKoZeEceZuTqRAph8EgV4SpphPdzET9sViMBH4jl4SmkT5Lh7MbFszhOZ64Dt6SRhjfnF2t" +
            "uPLXUyDIAD0kpCZUTEDVEMvCU3mKfT1AsXQS8JKNxNiSqAU2kmYd9xZHNkLVEI7CbOOM1PIhz0QABpoJ" +
            "2FJ3AKezQCV0ExC5ozjzOYxEwKF0EtCIrJFbAc13EAh9JKQieZcN4s1IVAJvSQkoqK4LrqZgEpoJ+EgG" +
            "8/PXAp7FAA00E5CkyiHp6NAJbSTMMF8It15DTcAvqOdhMxUxNNRoBLaSRhj49lLWBMChdBOQiYquNj1E" +
            "CiEdhIazL+Ymwt7FAA00E5CJiIbW48ChdBOQiIiNqayOLweqIKWEhLZWBYCZdBSQoNPzSBVCFRBSwmJX" +
            "UGqEKiCjhIaTBewJgTKoKOEceJcqRT2KACooqOEFnM6lwt7FABU0VFCk6iImRAog5YSMqdxVChQBh0lt" +
            "IjOF/I2NgEGaqCjhMxkuy524gaKoKOEFvGpbAa7jwJF0FFCwkmfQCV0lNBkfjGbxRlpQBF0lJCJHBFMh" +
            "0ARtJSQ+WSx4DhopABKoKWERE7ZxtNRoAg6SkhExJxB0QxQA30lPINzs4Ea6CohEaJRoAiaSphiPjWL5" +
            "nqgBJpKaBA5aK4HaqCphBbzTL4Q9igAINJZwovo6wVqoKmEHPYAAKijqYQm83mkKIAaaCohE5VRtgbUQ" +
            "F8JHSQKgRpoKqHBfKFUTKNyDSiAphISkUFsMB7QgPDRVEImKomLZSFQAU0lNIgulkozBW/5esybIAg0l" +
            "ZCIDGav0WjetmEi8B0r7AGEhiPiut4ekP7fhfNEVMZj1VXBqPxDGfYwVgFNJTSYLpbKmaK3cPT56elrB" +
            "weTpqZ/aauJwXS+VLpYLr9k22OmmTSiHLJp+35il8T1OKe979rr333NtYhIVwGDaWouM5vLnZq++Njzz" +
            "x0+c4ZMY5NpJaJoo7YSEhOxR536YrGABgMWMjg8TMPD12ze/OZfeVXWtp84evTRXzzzjampMcuK2MQYq" +
            "T+MJ3KuW3aw9Whv0G9ZD+zf/7UH3/qde++7fv36Sdt2I7RjpaYSMtGMbeOAtN4iZhh379r92AMPfuz6G" +
            "6Zsu+hGpC1bUwlB79Ifi733uut/+pa37RgcvBiJbdQhIehJ9m8c+de3vO2t23ec7P1wRmsJUTva0wwlE" +
            "p+6977379o93ePzob4SmsyT2UzYowBdETOMj99739t37DxV7uH5UF8Jk0wv5/NhjwJ0i0n08Xte/65tO" +
            "3p3faivhERkIO0eCWKG8dE7737VwGCxNysKtZYQRIahZPJz993/cqHQi1kLSAgiwuUbNjxy400v5nLUa" +
            "8/bICGIDr9x/Q2/NbYp3WseQkIQHZjoQwfvLOfzbqnUQx5CQhApLt+w8cO/esPkpUvUOx5qLSGS9ZHk/" +
            "a+7zbBMO5ORHvFQ31amPjaOz1x6+uwEtntSCiYaHxoaGVwT67RfKWGan7zl1od+8P0N2SwTUTyu+GGUv" +
            "P3TD4c9htDIOM55GKgaImTwOzaPf+TW23dedlln93g5kzn4mb+9WCpabBgDAxSLqeyh1hICNRGinOO8b" +
            "NtfO3jXm/Yf6OwmH/nOt/766Z+sj8eJiPv7WeH5UOs1IVATJuo3zfF4/P3//sOv/+Lnnd3kHVdfG7Ms1" +
            "3WJSLJZldeH+q4JF+KIZL1uwAaCxBZ58xPfPrJu/ZVjY16v3bp+/a+Nb/3GqZMDzMQs2SwzqxmXQsIqj" +
            "siWvv7bx8cRGyiFI/Ifp0/tHxnx+pwmZhgH913x+ePH+k2TRYjZzWSM/n4Fn9NAwipFkQPDwx++7Q4z7" +
            "JEAv7hn/wE6/LiIEHPVw2yWiVRbH+Lf/QZC4kZl2xJARGtTqbfu3JV3HBISoop4ks1SuazUvpWQsIHFR" +
            "se5KaAm9+7ePe04RNLsoZvJkF1W5zkNwtEqKcN4cvLcjV96VKEwBdQQEiE6/MCDI/39ni48ML51nWmKC" +
            "DORsDDV14fq5C0gYRUmKjnOmbl0+D8T0AaZsO3vHzv6tiuv8nTZgU2b1lnxOadsEhNLs4eSzZIa60NI2" +
            "ICJLGVCFDAfHjOtfz527NevvMrTTyhmGLs3rP/x2XOmJSRtPFQhbwEJW3FEcng8oySHTp86l06/Ys0aT" +
            "1fdunPnd8+cTkq8YmCLhyrEpZBwHo7IaCp1++iYDQ/Vo+A4Jy5Ne5XwyrFNBcehWN1Aovnrw9DjUkg4j" +
            "6LrXjky+uf3vD7sgQDfGB1auzYeFxFmrhlI7eNSK0ZhHHGBJ/KtOJgDo0V/KrW1r88RIRKqZSrqv6qQt" +
            "4CErZhIFUaLwVRqLNVnuyLVaLNuoCz0MJQ6b4Sj80gaxtOT597z+NdsFHIrSaZc/quDd21bt27llwwkE" +
            "usSSUcqvgkzE1XWh4vEpbTafcCQcB4G86Vi8fC5c2EPBLTnpVLpXZemPUloMQ8nE05FqoaHDQNbn5dms" +
            "8bq5i0gYSsGcx+yhaqSMs2JuTmvV/UlU44IiRBzzUMiorqB4eYtIGEbyuL5OHuwOuRFzmY8Szg00G9XZ" +
            "8JmD+txach5C0jYii2yb+1la+LxKB3IHBmKjrNp0FuekIik+mi0+sl8D2mZvEXwcSkkbOVMuXz4joOv3" +
            "jgS9kCAfwhVn4VWOpi8xKWr0AeMx/FtKPXsIVtgEWqxKEnTx5U8xXJ5i+D3p8FM2IZKth7BqJp0aEPzm" +
            "rD+FU9xaWD1NJCwlU2W9Zmnf3IolYKEClJ2nNdu3/HAvis6ubhqnRDTInEpL5q3yGSC278UEraSMIzvn" +
            "Z0o4+moklyw7XWDgw94vIordlGLh0TEi68PW5+XBpe3gIRtSBpGMuwxgLbkXHesf8DrVbPZjMX1aLPuY" +
            "e1L7fMW7eNSCiBvAQlbcUUwDSpLznFeMeBZwmwuZxI12dXsIREttj5cpT5gSDgPV2Qontg7fJkDD5UkX" +
            "S7v27DB0yVl172Yz9fe6As9rHx9ibg08HoaSDiPorjXjI7+w333Q0I1ERGvbS75UildLBrUFIK2mQ+Xi" +
            "EsDr6eBhPOoRygmykfVxPvPZSaXO5PJmNXJbQkPm16wunkLJOtbsRh/J5Eik8+9kM2YXEvUz8vON+UPm" +
            "+vaqJ7HX40+YMyE80iZxlNnJ+78ypdRwK0gabv8ZzfdfOeOnZ6uujibzhYLw6m+WsxJRIvNh5UrPMSlv" +
            "qwPIeE8mDhvl5+dvhj2QEAbzhaL+9av93rVUy8cTxhmdY+Z5T1cLC4NsA8YErbCxHEDC0LlKLruXZs2b" +
            "V4z5PXCn545PWAYleCy4SEtsT6kdvU0AfYBQ8IGjkhB6juRALU479if2P9Kr/86Fmz7mYmJeGWd3+yhV" +
            "B/UeIlLK1f4n7eAhFUckZFE4voNGw1G7bZyVJ6Q3Lprl9cLnzn94oVyacA06+Uy8+bDZeLSVcpbQMIqR" +
            "ZFrNo48/IY3hj0Q4CfHJybStj1omI3mCw9xaad5C49xKR7HN3DELWPT0Wjx1f85MmyaRCIijQBH5m9/6" +
            "HvewmP/ISRsYOJ8wmiRzue/eez5ZPVnWvNQ6p/VxKNlPQy2DxjhaJUk83+//NJ7D/2LwaEflQUaOCKbh" +
            "oY+dMvrEqbn9+q3nzlClYizFnCKEDcFmV7Wh9VLPMSltNK8BSSsYjCfLxYfPzsBAdXBFblQyP/s7b/Zg" +
            "YG2uE8cObImFqudQtHkITHVqti6y1vQUn3AK85bQMIG2HFUKcoiM6576L77Xz021sHlz589+4VfPjsWj" +
            "xNRew9pwfPSbvMWHdbTWPiHHyhI1nEuSyQ+8brb3ri3o50siB770Y/MilWV+HChhx3Gpf73AVtzjtPZH" +
            "xKAIKg8BnnNhg2fPHj3juHhzm7yUjp96Jkj60yr2R+f4lL/+4Ct7z34ls7+nAAEgYgMp/q2DXkuT2vmi" +
            "//2w1+m02OJROWOnj1c3XoaRpUWiBiZYnHwod8ZSSQMwyCqhZ1Nv877CnHt0/pn1Y+qv9Q/rb2g+dqmr" +
            "xC3eWXN8cr3XcRDpMVA1Pi77z5BRAZXc03SyPhRm6/Q/Grhlvxh08sW5A9p3gsa+cN6KpJa8oeSzVK5v" +
            "HDAkBBEiuNTUx/4zrdG6hPOyj1ctXoa227J40NCEB1KjvMHj31xgGubI3Tg4SrU0yw4DxgSgujwhe8/e" +
            "eiF4wOVzP7S1nmNS5fysHFJ9fdbX0kL49JmDyEhiAhHz517z+Nf32hatd22O/WwbVzafMOVxqX1S9vEp" +
            "dX1ITNBQhANzs/N3f03Hx022GRumrW68HBhXLr8+nBhXLrM+rAyH0JC0PPM5nK//7lHTs3NJdhovO+79" +
            "JA6WB9SOw+pycDW9WElLoWEoLcplMsPPfLZL/38f0djMaJm9/zwkOqfrTAupXkvWEneIpdDsh70MC7Jm" +
            "/7yLw4de340kaxlzusJ9JZs+/w8+8Ks/WJ5/PpTTA95/Jbv2JLHb/xa/ZaQEPQoExcvPvTI33/96HMji" +
            "WS1KqXVQ6q+47v0kIKtp4GEoCf58dHnPvDoF/5zcnIkkWgqDFvoYS/Mh5AQ9BZC9PA3D//uP311IJHoN" +
            "63mNzQ3Pl4tD5vFW6mH9am1NmxICHqFsut+68f/9b4vf/HcbHpDKsVsVAO65jc09V5cCgmB6tiuOzU9/" +
            "eSRn33+B08+NTExFIslDIOYm5ZVK/EwxLiUlvQQEgJVmZ6be+bUyWdPnvzZ0aNPvHDs7KWZgWQiaVrMT" +
            "QIs5mFPxaW87cN/VJ6aYmz1B5TBFTk3NUm2TbEYJZJkWWtN0zKMeXZx/WNlPJx3Zw/zoeWOjpay2dLkJ" +
            "DwE6rB+aC0RieMQEVuVgmyiamd8pfNdhJgqPfBMJFz5r97YLsKVjdCIqamhnogqF9U2qpCmfStkQff9w" +
            "q/Q4vtEUYf701gm0cDOnQXm0uQkm2Yof+MAtIVNUxxHHIcNc55dNQ9rb/dFPKy+2Vs8rLhH3XpYn0u73" +
            "p+mOvslL788tnGjYNMnoBhsmiIibuWdWSv3qpdES/3jelnmvILpxivnFaa1VIF2UedN9c9WXufd/BUSk" +
            "VoI6rp9e/fGx8YEhzEAxTBMk0TEtoloMQ8r/y/qobT10I8677pWXfQBN9aB4jjJHTvgIVCQykKpFqm18" +
            "bD29UU8pLYeVi8Kqs57KQ/rrxFa2E+Y3LEDcSlQkGpcuriH0nijL+LhKselzTdcst9iwRNRkb49e2IjI" +
            "5gPgWoYy3so1ElcGpiHy68P282ERCSOk9q1C3EpUJDa+nBxD2nJ9SEt5mFY60OiRbe3EElu3x4fHUVcC" +
            "lSDTVNoqfmw+jpvcWn1ZkGtD2kJDxeGo00gbwHUZEVx6RLPaRofKxGXLlkl47qpPXsQlwIFiVLeYrlSN" +
            "ddF3gKoSSNv0XaWa7zdPa0PqxcFFZe283BF9aLIWwA1WVk9jdf1YZBxafMNa996ZUXbIn179sRHRzEfA" +
            "tVYQVxaS114i0t98nBhXLpgfbjSzglxnOTOnYhLgYKsqJ5mCQ8pSA/rLB6XemtfQt4CqMny9TSV1ykZl" +
            "3ruIUzt2oX1IVCQ3s1beJZQHCe1e3d80ybEpUA1ejRv0VE3faWeZmwM8yFQDR/yFm3mw+pFAa0PO9/SI" +
            "rlzJ+JSoCA91wfcxb4y6AMGqtJbcWlXmzuhDxgoSzB5i+rN/I1LfdhhLbl9e2xkBHEpUI1eyVv4s81h3" +
            "+7d6AMGCtITfcD+SIg+YKAsqvcB+3lmPfqAgaqwaRKp2gfcYZ5wcdAHDNRkBftEVQxcPC4NbH3o99b3r" +
            "tu3d29y2zZCXAoUQ9m8hf/nT4jjxDdvTmzdCg+BaqjZBxzMITAi8S1b4lu2IC4FqqFgH3BgJzG5bnL79" +
            "iTmQ6AeqvUBB3gcmth2fMsWxKVAQVZST9NR3qITDwM+k1Cksj5EXApUY9nnpdXXBR+XBn8wqEhi69bE+" +
            "Djy+EA1FOkDXo3TecW2k1u3Yn0IFESFvMUqHZEtrluNS+EhUIzQ+4BX8Zx6kcSWLQnkLYB6dJu36C4uX" +
            "UUJiaSSt0A9DVCPwPIWy8elqyohEYlto54GqElYfcCrLWHlG8c3b06MjyMuBaoRSh9wGBISkUhi27bE+" +
            "DjmQ6Aaq98HHJKERGLbia1bEZcCBVl+fUhL5i3I2/owNAmJiOp5C8SlQDFWM28RqoREJJIYH8f6ECjIq" +
            "u1fGraEROI4yW3bkLcACrI69TThS0iEPmCgLivKWywdly6Xt1BCQiIi9AEDVVnB/jSV3+kwb6GMhIQ+Y" +
            "KAuy++b2EXeQiUJicS24+PjiEuBgiy7b2KneQvFJCRC3gKoS0B9wOpJSE15C8yHQDGC6ANWUsJK3gJ9w" +
            "EBJfM9bKCohUaMPGB4C1fC3nkZdCYmIRBLIWwAl8bEPWG0JqdYHjPkQqIdffcCqS0iE/UuBuvjQB6zo0" +
            "9GFoA8YqEq3fcA9MRNWQR8wUJUu8xa9IyGhDxioSzd5i16SkAj1NEBdOs5b9JqE1FRPAw+BYnTWB9yDE" +
            "hL6gIG6dBCX9qSEROgDBuritQ+4VyUkIvQBA2Xx1AfcyxIS+oCBulTzFivoA+5xCQl9wEBdjBX0Aff+T" +
            "FgBeQugKiuJSyMhISFvAdRl2XqaqEiIvAVQmKXzFtbJUinU4fkKE23cSKUinTgZ9lAAaIKJiMh2iJlMk" +
            "5iImJiJiJj5qePHwhxcEDC76TTmQ6AiIlX3ql4SMf0/sUHOtYFBT6cAAAAASUVORK5CYII=")]
        public string EmailLogo {
            get {
                return ((string)(this["EmailLogo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://auth.taaghche.ir/connect/token")]
        public string ApiAuthServerUrl {
            get {
                return ((string)(this["ApiAuthServerUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("api")]
        public string ApiClientId {
            get {
                return ((string)(this["ApiClientId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d4Zor9pmS2D12R5DzHk9")]
        public string ApiClientSecret {
            get {
                return ((string)(this["ApiClientSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("client_credentials")]
        public string ApiAuthGrantType {
            get {
                return ((string)(this["ApiAuthGrantType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("service")]
        public string ApiAuthScope {
            get {
                return ((string)(this["ApiAuthScope"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("331602122:AAE73HowIucecPTtXHybgCUtgs14VzrDPKY")]
        public string TelegramBotApiKey {
            get {
                return ((string)(this["TelegramBotApiKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("@taaghche_notification_bot")]
        public string TelegramBotUsername {
            get {
                return ((string)(this["TelegramBotUsername"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50001760")]
        public string RahyabUserName {
            get {
                return ((string)(this["RahyabUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HojjateTak")]
        public string RahyabPassword {
            get {
                return ((string)(this["RahyabPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50001760")]
        public string RahyabSendNumber {
            get {
                return ((string)(this["RahyabSendNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=taaghche.hasintech.com;Initial Catalog=task;Persist Security Info=Tru" +
            "e;User ID=sa;Password=hasin#123456;")]
        public string ServerConnectionString {
            get {
                return ((string)(this["ServerConnectionString"]));
            }
        }
    }
}
