//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace Hasin.Taaghche.TaskScheduler.Service_References.GamamnSmsService {
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [CollectionDataContract(Name="ArrayOfString", Namespace="http://gamavas.ir/", ItemName="string")]
    [Serializable()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [CollectionDataContract(Name="ArrayOfBoolean", Namespace="http://gamavas.ir/", ItemName="boolean")]
    [Serializable()]
    public class ArrayOfBoolean : System.Collections.Generic.List<bool> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="DataSendIn", Namespace="http://gamavas.ir/")]
    [Serializable()]
    public partial class DataSendIn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long ClientIDField;
        
        [OptionalField()]
        private string ShortCodeField;
        
        [OptionalField()]
        private string CellphoneField;
        
        [OptionalField()]
        private string MessageField;
        
        private bool FarsiField;
        
        private bool FlashField;
        
        [OptionalField()]
        private string UDHField;
        
        [OptionalField()]
        private string ServiceIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(IsRequired=true)]
        public long ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string ShortCode {
            get {
                return this.ShortCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortCodeField, value) != true)) {
                    this.ShortCodeField = value;
                    this.RaisePropertyChanged("ShortCode");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Cellphone {
            get {
                return this.CellphoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CellphoneField, value) != true)) {
                    this.CellphoneField = value;
                    this.RaisePropertyChanged("Cellphone");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [DataMember(IsRequired=true, Order=4)]
        public bool Farsi {
            get {
                return this.FarsiField;
            }
            set {
                if ((this.FarsiField.Equals(value) != true)) {
                    this.FarsiField = value;
                    this.RaisePropertyChanged("Farsi");
                }
            }
        }
        
        [DataMember(IsRequired=true, Order=5)]
        public bool Flash {
            get {
                return this.FlashField;
            }
            set {
                if ((this.FlashField.Equals(value) != true)) {
                    this.FlashField = value;
                    this.RaisePropertyChanged("Flash");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=6)]
        public string UDH {
            get {
                return this.UDHField;
            }
            set {
                if ((object.ReferenceEquals(this.UDHField, value) != true)) {
                    this.UDHField = value;
                    this.RaisePropertyChanged("UDH");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=7)]
        public string ServiceID {
            get {
                return this.ServiceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceIDField, value) != true)) {
                    this.ServiceIDField = value;
                    this.RaisePropertyChanged("ServiceID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="DataSendOut", Namespace="http://gamavas.ir/")]
    [Serializable()]
    public partial class DataSendOut : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long ClientIDField;
        
        private long ServerIDField;
        
        [OptionalField()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(IsRequired=true)]
        public long ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [DataMember(IsRequired=true)]
        public long ServerID {
            get {
                return this.ServerIDField;
            }
            set {
                if ((this.ServerIDField.Equals(value) != true)) {
                    this.ServerIDField = value;
                    this.RaisePropertyChanged("ServerID");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="MessageReceive", Namespace="http://gamavas.ir/")]
    [Serializable()]
    public partial class MessageReceive : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long RowIDField;
        
        [OptionalField()]
        private string DateTimeField;
        
        [OptionalField()]
        private string SenderField;
        
        [OptionalField()]
        private string ReceiverField;
        
        [OptionalField()]
        private string MessageField;
        
        [OptionalField()]
        private string UDHField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(IsRequired=true)]
        public long RowID {
            get {
                return this.RowIDField;
            }
            set {
                if ((this.RowIDField.Equals(value) != true)) {
                    this.RowIDField = value;
                    this.RaisePropertyChanged("RowID");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DateTimeField, value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverField, value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false, Order=5)]
        public string UDH {
            get {
                return this.UDHField;
            }
            set {
                if ((object.ReferenceEquals(this.UDHField, value) != true)) {
                    this.UDHField = value;
                    this.RaisePropertyChanged("UDH");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gamavas.ir/", ConfigurationName="GamamnSmsService.smsSoap")]
    public interface smsSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/HelloWorld", ReplyAction="*")]
        HelloWorldResponse HelloWorld(HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloWorldResponse> HelloWorldAsync(HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doGetInfo", ReplyAction="*")]
        doGetInfoResponse doGetInfo(doGetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doGetInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<doGetInfoResponse> doGetInfoAsync(doGetInfoRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doSendSMS", ReplyAction="*")]
        doSendSMSResponse doSendSMS(doSendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doSendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<doSendSMSResponse> doSendSMSAsync(doSendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doSendArraySMS", ReplyAction="*")]
        doSendArraySMSResponse doSendArraySMS(doSendArraySMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doSendArraySMS", ReplyAction="*")]
        System.Threading.Tasks.Task<doSendArraySMSResponse> doSendArraySMSAsync(doSendArraySMSRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doSendSMSArrayC", ReplyAction="*")]
        doSendSMSArrayCResponse doSendSMSArrayC(doSendSMSArrayCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doSendSMSArrayC", ReplyAction="*")]
        System.Threading.Tasks.Task<doSendSMSArrayCResponse> doSendSMSArrayCAsync(doSendSMSArrayCRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doCheckClientID", ReplyAction="*")]
        doCheckClientIDResponse doCheckClientID(doCheckClientIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doCheckClientID", ReplyAction="*")]
        System.Threading.Tasks.Task<doCheckClientIDResponse> doCheckClientIDAsync(doCheckClientIDRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doGetDelivery", ReplyAction="*")]
        doGetDeliveryResponse doGetDelivery(doGetDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doGetDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<doGetDeliveryResponse> doGetDeliveryAsync(doGetDeliveryRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doGetDeliveryOlder", ReplyAction="*")]
        doGetDeliveryOlderResponse doGetDeliveryOlder(doGetDeliveryOlderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doGetDeliveryOlder", ReplyAction="*")]
        System.Threading.Tasks.Task<doGetDeliveryOlderResponse> doGetDeliveryOlderAsync(doGetDeliveryOlderRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doReceiveSMS", ReplyAction="*")]
        doReceiveSMSResponse doReceiveSMS(doReceiveSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doReceiveSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<doReceiveSMSResponse> doReceiveSMSAsync(doReceiveSMSRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doReceiveSMSArray", ReplyAction="*")]
        doReceiveSMSArrayResponse doReceiveSMSArray(doReceiveSMSArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/doReceiveSMSArray", ReplyAction="*")]
        System.Threading.Tasks.Task<doReceiveSMSArrayResponse> doReceiveSMSArrayAsync(doReceiveSMSArrayRequest request);
        
        // CODEGEN: Generating message contract since element name uUsername from namespace http://gamavas.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/getInfoXML", ReplyAction="*")]
        getInfoXMLResponse getInfoXML(getInfoXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gamavas.ir/getInfoXML", ReplyAction="*")]
        System.Threading.Tasks.Task<getInfoXMLResponse> getInfoXMLAsync(getInfoXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://gamavas.ir/", Order=0)]
        public HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://gamavas.ir/", Order=0)]
        public HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class HelloWorldResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doGetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doGetInfo", Namespace="http://gamavas.ir/", Order=0)]
        public doGetInfoRequestBody Body;
        
        public doGetInfoRequest() {
        }
        
        public doGetInfoRequest(doGetInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doGetInfoRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        public doGetInfoRequestBody() {
        }
        
        public doGetInfoRequestBody(string uUsername, string uPassword) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doGetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doGetInfoResponse", Namespace="http://gamavas.ir/", Order=0)]
        public doGetInfoResponseBody Body;
        
        public doGetInfoResponse() {
        }
        
        public doGetInfoResponse(doGetInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doGetInfoResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string doGetInfoResult;
        
        public doGetInfoResponseBody() {
        }
        
        public doGetInfoResponseBody(string doGetInfoResult) {
            this.doGetInfoResult = doGetInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMS", Namespace="http://gamavas.ir/", Order=0)]
        public doSendSMSRequestBody Body;
        
        public doSendSMSRequest() {
        }
        
        public doSendSMSRequest(doSendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doSendSMSRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string uNumber;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public string uCellphones;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public string uMessage;
        
        [DataMember(Order=5)]
        public bool uFarsi;
        
        [DataMember(Order=6)]
        public bool uTopic;
        
        [DataMember(Order=7)]
        public bool uFlash;
        
        [DataMember(EmitDefaultValue=false, Order=8)]
        public string uUDH;
        
        public doSendSMSRequestBody() {
        }
        
        public doSendSMSRequestBody(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi, bool uTopic, bool uFlash, string uUDH) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uNumber = uNumber;
            this.uCellphones = uCellphones;
            this.uMessage = uMessage;
            this.uFarsi = uFarsi;
            this.uTopic = uTopic;
            this.uFlash = uFlash;
            this.uUDH = uUDH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMSResponse", Namespace="http://gamavas.ir/", Order=0)]
        public doSendSMSResponseBody Body;
        
        public doSendSMSResponse() {
        }
        
        public doSendSMSResponse(doSendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doSendSMSResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string doSendSMSResult;
        
        public doSendSMSResponseBody() {
        }
        
        public doSendSMSResponseBody(string doSendSMSResult) {
            this.doSendSMSResult = doSendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendArraySMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendArraySMS", Namespace="http://gamavas.ir/", Order=0)]
        public doSendArraySMSRequestBody Body;
        
        public doSendArraySMSRequest() {
        }
        
        public doSendArraySMSRequest(doSendArraySMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doSendArraySMSRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public ArrayOfString uNumber;
        
        [DataMember(EmitDefaultValue=false, Order=3)]
        public ArrayOfString uCellphone;
        
        [DataMember(EmitDefaultValue=false, Order=4)]
        public ArrayOfString uMessage;
        
        [DataMember(EmitDefaultValue=false, Order=5)]
        public ArrayOfBoolean uFarsi;
        
        [DataMember(EmitDefaultValue=false, Order=6)]
        public ArrayOfBoolean uTopic;
        
        [DataMember(EmitDefaultValue=false, Order=7)]
        public ArrayOfBoolean uFlash;
        
        [DataMember(EmitDefaultValue=false, Order=8)]
        public ArrayOfString uUDH;
        
        public doSendArraySMSRequestBody() {
        }
        
        public doSendArraySMSRequestBody(string uUsername, string uPassword, ArrayOfString uNumber, ArrayOfString uCellphone, ArrayOfString uMessage, ArrayOfBoolean uFarsi, ArrayOfBoolean uTopic, ArrayOfBoolean uFlash, ArrayOfString uUDH) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uNumber = uNumber;
            this.uCellphone = uCellphone;
            this.uMessage = uMessage;
            this.uFarsi = uFarsi;
            this.uTopic = uTopic;
            this.uFlash = uFlash;
            this.uUDH = uUDH;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendArraySMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendArraySMSResponse", Namespace="http://gamavas.ir/", Order=0)]
        public doSendArraySMSResponseBody Body;
        
        public doSendArraySMSResponse() {
        }
        
        public doSendArraySMSResponse(doSendArraySMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doSendArraySMSResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string doSendArraySMSResult;
        
        public doSendArraySMSResponseBody() {
        }
        
        public doSendArraySMSResponseBody(string doSendArraySMSResult) {
            this.doSendArraySMSResult = doSendArraySMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSArrayCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMSArrayC", Namespace="http://gamavas.ir/", Order=0)]
        public doSendSMSArrayCRequestBody Body;
        
        public doSendSMSArrayCRequest() {
        }
        
        public doSendSMSArrayCRequest(doSendSMSArrayCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doSendSMSArrayCRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public DataSendIn[] uDataSendIn;
        
        public doSendSMSArrayCRequestBody() {
        }
        
        public doSendSMSArrayCRequestBody(string uUsername, string uPassword, DataSendIn[] uDataSendIn) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uDataSendIn = uDataSendIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doSendSMSArrayCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doSendSMSArrayCResponse", Namespace="http://gamavas.ir/", Order=0)]
        public doSendSMSArrayCResponseBody Body;
        
        public doSendSMSArrayCResponse() {
        }
        
        public doSendSMSArrayCResponse(doSendSMSArrayCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doSendSMSArrayCResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public DataSendOut[] doSendSMSArrayCResult;
        
        public doSendSMSArrayCResponseBody() {
        }
        
        public doSendSMSArrayCResponseBody(DataSendOut[] doSendSMSArrayCResult) {
            this.doSendSMSArrayCResult = doSendSMSArrayCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doCheckClientIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doCheckClientID", Namespace="http://gamavas.ir/", Order=0)]
        public doCheckClientIDRequestBody Body;
        
        public doCheckClientIDRequest() {
        }
        
        public doCheckClientIDRequest(doCheckClientIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doCheckClientIDRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string uClientIDs;
        
        public doCheckClientIDRequestBody() {
        }
        
        public doCheckClientIDRequestBody(string uUsername, string uClientIDs) {
            this.uUsername = uUsername;
            this.uClientIDs = uClientIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doCheckClientIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doCheckClientIDResponse", Namespace="http://gamavas.ir/", Order=0)]
        public doCheckClientIDResponseBody Body;
        
        public doCheckClientIDResponse() {
        }
        
        public doCheckClientIDResponse(doCheckClientIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doCheckClientIDResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string doCheckClientIDResult;
        
        public doCheckClientIDResponseBody() {
        }
        
        public doCheckClientIDResponseBody(string doCheckClientIDResult) {
            this.doCheckClientIDResult = doCheckClientIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doGetDeliveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doGetDelivery", Namespace="http://gamavas.ir/", Order=0)]
        public doGetDeliveryRequestBody Body;
        
        public doGetDeliveryRequest() {
        }
        
        public doGetDeliveryRequest(doGetDeliveryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doGetDeliveryRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string uReturnIDs;
        
        public doGetDeliveryRequestBody() {
        }
        
        public doGetDeliveryRequestBody(string uUsername, string uReturnIDs) {
            this.uUsername = uUsername;
            this.uReturnIDs = uReturnIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doGetDeliveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doGetDeliveryResponse", Namespace="http://gamavas.ir/", Order=0)]
        public doGetDeliveryResponseBody Body;
        
        public doGetDeliveryResponse() {
        }
        
        public doGetDeliveryResponse(doGetDeliveryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doGetDeliveryResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string doGetDeliveryResult;
        
        public doGetDeliveryResponseBody() {
        }
        
        public doGetDeliveryResponseBody(string doGetDeliveryResult) {
            this.doGetDeliveryResult = doGetDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doGetDeliveryOlderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doGetDeliveryOlder", Namespace="http://gamavas.ir/", Order=0)]
        public doGetDeliveryOlderRequestBody Body;
        
        public doGetDeliveryOlderRequest() {
        }
        
        public doGetDeliveryOlderRequest(doGetDeliveryOlderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doGetDeliveryOlderRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string uReturnIDs;
        
        public doGetDeliveryOlderRequestBody() {
        }
        
        public doGetDeliveryOlderRequestBody(string uUsername, string uReturnIDs) {
            this.uUsername = uUsername;
            this.uReturnIDs = uReturnIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doGetDeliveryOlderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doGetDeliveryOlderResponse", Namespace="http://gamavas.ir/", Order=0)]
        public doGetDeliveryOlderResponseBody Body;
        
        public doGetDeliveryOlderResponse() {
        }
        
        public doGetDeliveryOlderResponse(doGetDeliveryOlderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doGetDeliveryOlderResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string doGetDeliveryOlderResult;
        
        public doGetDeliveryOlderResponseBody() {
        }
        
        public doGetDeliveryOlderResponseBody(string doGetDeliveryOlderResult) {
            this.doGetDeliveryOlderResult = doGetDeliveryOlderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMS", Namespace="http://gamavas.ir/", Order=0)]
        public doReceiveSMSRequestBody Body;
        
        public doReceiveSMSRequest() {
        }
        
        public doReceiveSMSRequest(doReceiveSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doReceiveSMSRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [DataMember(Order=2)]
        public long uLastRowID;
        
        public doReceiveSMSRequestBody() {
        }
        
        public doReceiveSMSRequestBody(string uUsername, string uPassword, long uLastRowID) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uLastRowID = uLastRowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMSResponse", Namespace="http://gamavas.ir/", Order=0)]
        public doReceiveSMSResponseBody Body;
        
        public doReceiveSMSResponse() {
        }
        
        public doReceiveSMSResponse(doReceiveSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doReceiveSMSResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string doReceiveSMSResult;
        
        public doReceiveSMSResponseBody() {
        }
        
        public doReceiveSMSResponseBody(string doReceiveSMSResult) {
            this.doReceiveSMSResult = doReceiveSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSArrayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMSArray", Namespace="http://gamavas.ir/", Order=0)]
        public doReceiveSMSArrayRequestBody Body;
        
        public doReceiveSMSArrayRequest() {
        }
        
        public doReceiveSMSArrayRequest(doReceiveSMSArrayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doReceiveSMSArrayRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        [DataMember(Order=2)]
        public long uLastRowID;
        
        public doReceiveSMSArrayRequestBody() {
        }
        
        public doReceiveSMSArrayRequestBody(string uUsername, string uPassword, long uLastRowID) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
            this.uLastRowID = uLastRowID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doReceiveSMSArrayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doReceiveSMSArrayResponse", Namespace="http://gamavas.ir/", Order=0)]
        public doReceiveSMSArrayResponseBody Body;
        
        public doReceiveSMSArrayResponse() {
        }
        
        public doReceiveSMSArrayResponse(doReceiveSMSArrayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class doReceiveSMSArrayResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public MessageReceive[] doReceiveSMSArrayResult;
        
        public doReceiveSMSArrayResponseBody() {
        }
        
        public doReceiveSMSArrayResponseBody(MessageReceive[] doReceiveSMSArrayResult) {
            this.doReceiveSMSArrayResult = doReceiveSMSArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfoXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoXML", Namespace="http://gamavas.ir/", Order=0)]
        public getInfoXMLRequestBody Body;
        
        public getInfoXMLRequest() {
        }
        
        public getInfoXMLRequest(getInfoXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class getInfoXMLRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string uUsername;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string uPassword;
        
        public getInfoXMLRequestBody() {
        }
        
        public getInfoXMLRequestBody(string uUsername, string uPassword) {
            this.uUsername = uUsername;
            this.uPassword = uPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfoXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfoXMLResponse", Namespace="http://gamavas.ir/", Order=0)]
        public getInfoXMLResponseBody Body;
        
        public getInfoXMLResponse() {
        }
        
        public getInfoXMLResponse(getInfoXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://gamavas.ir/")]
    public partial class getInfoXMLResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string getInfoXMLResult;
        
        public getInfoXMLResponseBody() {
        }
        
        public getInfoXMLResponseBody(string getInfoXMLResult) {
            this.getInfoXMLResult = getInfoXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smsSoapChannel : smsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smsSoapClient : System.ServiceModel.ClientBase<smsSoap>, smsSoap {
        
        public smsSoapClient() {
        }
        
        public smsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloWorldResponse smsSoap.HelloWorld(HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            HelloWorldRequest inValue = new HelloWorldRequest();
            inValue.Body = new HelloWorldRequestBody();
            HelloWorldResponse retVal = ((smsSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloWorldResponse> smsSoap.HelloWorldAsync(HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloWorldResponse> HelloWorldAsync() {
            HelloWorldRequest inValue = new HelloWorldRequest();
            inValue.Body = new HelloWorldRequestBody();
            return ((smsSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        doGetInfoResponse smsSoap.doGetInfo(doGetInfoRequest request) {
            return base.Channel.doGetInfo(request);
        }
        
        public string doGetInfo(string uUsername, string uPassword) {
            doGetInfoRequest inValue = new doGetInfoRequest();
            inValue.Body = new doGetInfoRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            doGetInfoResponse retVal = ((smsSoap)(this)).doGetInfo(inValue);
            return retVal.Body.doGetInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<doGetInfoResponse> smsSoap.doGetInfoAsync(doGetInfoRequest request) {
            return base.Channel.doGetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<doGetInfoResponse> doGetInfoAsync(string uUsername, string uPassword) {
            doGetInfoRequest inValue = new doGetInfoRequest();
            inValue.Body = new doGetInfoRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            return ((smsSoap)(this)).doGetInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        doSendSMSResponse smsSoap.doSendSMS(doSendSMSRequest request) {
            return base.Channel.doSendSMS(request);
        }
        
        public string doSendSMS(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi, bool uTopic, bool uFlash, string uUDH) {
            doSendSMSRequest inValue = new doSendSMSRequest();
            inValue.Body = new doSendSMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uNumber = uNumber;
            inValue.Body.uCellphones = uCellphones;
            inValue.Body.uMessage = uMessage;
            inValue.Body.uFarsi = uFarsi;
            inValue.Body.uTopic = uTopic;
            inValue.Body.uFlash = uFlash;
            inValue.Body.uUDH = uUDH;
            doSendSMSResponse retVal = ((smsSoap)(this)).doSendSMS(inValue);
            return retVal.Body.doSendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<doSendSMSResponse> smsSoap.doSendSMSAsync(doSendSMSRequest request) {
            return base.Channel.doSendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<doSendSMSResponse> doSendSMSAsync(string uUsername, string uPassword, string uNumber, string uCellphones, string uMessage, bool uFarsi, bool uTopic, bool uFlash, string uUDH) {
            doSendSMSRequest inValue = new doSendSMSRequest();
            inValue.Body = new doSendSMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uNumber = uNumber;
            inValue.Body.uCellphones = uCellphones;
            inValue.Body.uMessage = uMessage;
            inValue.Body.uFarsi = uFarsi;
            inValue.Body.uTopic = uTopic;
            inValue.Body.uFlash = uFlash;
            inValue.Body.uUDH = uUDH;
            return ((smsSoap)(this)).doSendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        doSendArraySMSResponse smsSoap.doSendArraySMS(doSendArraySMSRequest request) {
            return base.Channel.doSendArraySMS(request);
        }
        
        public string doSendArraySMS(string uUsername, string uPassword, ArrayOfString uNumber, ArrayOfString uCellphone, ArrayOfString uMessage, ArrayOfBoolean uFarsi, ArrayOfBoolean uTopic, ArrayOfBoolean uFlash, ArrayOfString uUDH) {
            doSendArraySMSRequest inValue = new doSendArraySMSRequest();
            inValue.Body = new doSendArraySMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uNumber = uNumber;
            inValue.Body.uCellphone = uCellphone;
            inValue.Body.uMessage = uMessage;
            inValue.Body.uFarsi = uFarsi;
            inValue.Body.uTopic = uTopic;
            inValue.Body.uFlash = uFlash;
            inValue.Body.uUDH = uUDH;
            doSendArraySMSResponse retVal = ((smsSoap)(this)).doSendArraySMS(inValue);
            return retVal.Body.doSendArraySMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<doSendArraySMSResponse> smsSoap.doSendArraySMSAsync(doSendArraySMSRequest request) {
            return base.Channel.doSendArraySMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<doSendArraySMSResponse> doSendArraySMSAsync(string uUsername, string uPassword, ArrayOfString uNumber, ArrayOfString uCellphone, ArrayOfString uMessage, ArrayOfBoolean uFarsi, ArrayOfBoolean uTopic, ArrayOfBoolean uFlash, ArrayOfString uUDH) {
            doSendArraySMSRequest inValue = new doSendArraySMSRequest();
            inValue.Body = new doSendArraySMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uNumber = uNumber;
            inValue.Body.uCellphone = uCellphone;
            inValue.Body.uMessage = uMessage;
            inValue.Body.uFarsi = uFarsi;
            inValue.Body.uTopic = uTopic;
            inValue.Body.uFlash = uFlash;
            inValue.Body.uUDH = uUDH;
            return ((smsSoap)(this)).doSendArraySMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        doSendSMSArrayCResponse smsSoap.doSendSMSArrayC(doSendSMSArrayCRequest request) {
            return base.Channel.doSendSMSArrayC(request);
        }
        
        public DataSendOut[] doSendSMSArrayC(string uUsername, string uPassword, DataSendIn[] uDataSendIn) {
            doSendSMSArrayCRequest inValue = new doSendSMSArrayCRequest();
            inValue.Body = new doSendSMSArrayCRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uDataSendIn = uDataSendIn;
            doSendSMSArrayCResponse retVal = ((smsSoap)(this)).doSendSMSArrayC(inValue);
            return retVal.Body.doSendSMSArrayCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<doSendSMSArrayCResponse> smsSoap.doSendSMSArrayCAsync(doSendSMSArrayCRequest request) {
            return base.Channel.doSendSMSArrayCAsync(request);
        }
        
        public System.Threading.Tasks.Task<doSendSMSArrayCResponse> doSendSMSArrayCAsync(string uUsername, string uPassword, DataSendIn[] uDataSendIn) {
            doSendSMSArrayCRequest inValue = new doSendSMSArrayCRequest();
            inValue.Body = new doSendSMSArrayCRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uDataSendIn = uDataSendIn;
            return ((smsSoap)(this)).doSendSMSArrayCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        doCheckClientIDResponse smsSoap.doCheckClientID(doCheckClientIDRequest request) {
            return base.Channel.doCheckClientID(request);
        }
        
        public string doCheckClientID(string uUsername, string uClientIDs) {
            doCheckClientIDRequest inValue = new doCheckClientIDRequest();
            inValue.Body = new doCheckClientIDRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uClientIDs = uClientIDs;
            doCheckClientIDResponse retVal = ((smsSoap)(this)).doCheckClientID(inValue);
            return retVal.Body.doCheckClientIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<doCheckClientIDResponse> smsSoap.doCheckClientIDAsync(doCheckClientIDRequest request) {
            return base.Channel.doCheckClientIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<doCheckClientIDResponse> doCheckClientIDAsync(string uUsername, string uClientIDs) {
            doCheckClientIDRequest inValue = new doCheckClientIDRequest();
            inValue.Body = new doCheckClientIDRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uClientIDs = uClientIDs;
            return ((smsSoap)(this)).doCheckClientIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        doGetDeliveryResponse smsSoap.doGetDelivery(doGetDeliveryRequest request) {
            return base.Channel.doGetDelivery(request);
        }
        
        public string doGetDelivery(string uUsername, string uReturnIDs) {
            doGetDeliveryRequest inValue = new doGetDeliveryRequest();
            inValue.Body = new doGetDeliveryRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uReturnIDs = uReturnIDs;
            doGetDeliveryResponse retVal = ((smsSoap)(this)).doGetDelivery(inValue);
            return retVal.Body.doGetDeliveryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<doGetDeliveryResponse> smsSoap.doGetDeliveryAsync(doGetDeliveryRequest request) {
            return base.Channel.doGetDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<doGetDeliveryResponse> doGetDeliveryAsync(string uUsername, string uReturnIDs) {
            doGetDeliveryRequest inValue = new doGetDeliveryRequest();
            inValue.Body = new doGetDeliveryRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uReturnIDs = uReturnIDs;
            return ((smsSoap)(this)).doGetDeliveryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        doGetDeliveryOlderResponse smsSoap.doGetDeliveryOlder(doGetDeliveryOlderRequest request) {
            return base.Channel.doGetDeliveryOlder(request);
        }
        
        public string doGetDeliveryOlder(string uUsername, string uReturnIDs) {
            doGetDeliveryOlderRequest inValue = new doGetDeliveryOlderRequest();
            inValue.Body = new doGetDeliveryOlderRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uReturnIDs = uReturnIDs;
            doGetDeliveryOlderResponse retVal = ((smsSoap)(this)).doGetDeliveryOlder(inValue);
            return retVal.Body.doGetDeliveryOlderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<doGetDeliveryOlderResponse> smsSoap.doGetDeliveryOlderAsync(doGetDeliveryOlderRequest request) {
            return base.Channel.doGetDeliveryOlderAsync(request);
        }
        
        public System.Threading.Tasks.Task<doGetDeliveryOlderResponse> doGetDeliveryOlderAsync(string uUsername, string uReturnIDs) {
            doGetDeliveryOlderRequest inValue = new doGetDeliveryOlderRequest();
            inValue.Body = new doGetDeliveryOlderRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uReturnIDs = uReturnIDs;
            return ((smsSoap)(this)).doGetDeliveryOlderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        doReceiveSMSResponse smsSoap.doReceiveSMS(doReceiveSMSRequest request) {
            return base.Channel.doReceiveSMS(request);
        }
        
        public string doReceiveSMS(string uUsername, string uPassword, long uLastRowID) {
            doReceiveSMSRequest inValue = new doReceiveSMSRequest();
            inValue.Body = new doReceiveSMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uLastRowID = uLastRowID;
            doReceiveSMSResponse retVal = ((smsSoap)(this)).doReceiveSMS(inValue);
            return retVal.Body.doReceiveSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<doReceiveSMSResponse> smsSoap.doReceiveSMSAsync(doReceiveSMSRequest request) {
            return base.Channel.doReceiveSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<doReceiveSMSResponse> doReceiveSMSAsync(string uUsername, string uPassword, long uLastRowID) {
            doReceiveSMSRequest inValue = new doReceiveSMSRequest();
            inValue.Body = new doReceiveSMSRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uLastRowID = uLastRowID;
            return ((smsSoap)(this)).doReceiveSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        doReceiveSMSArrayResponse smsSoap.doReceiveSMSArray(doReceiveSMSArrayRequest request) {
            return base.Channel.doReceiveSMSArray(request);
        }
        
        public MessageReceive[] doReceiveSMSArray(string uUsername, string uPassword, long uLastRowID) {
            doReceiveSMSArrayRequest inValue = new doReceiveSMSArrayRequest();
            inValue.Body = new doReceiveSMSArrayRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uLastRowID = uLastRowID;
            doReceiveSMSArrayResponse retVal = ((smsSoap)(this)).doReceiveSMSArray(inValue);
            return retVal.Body.doReceiveSMSArrayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<doReceiveSMSArrayResponse> smsSoap.doReceiveSMSArrayAsync(doReceiveSMSArrayRequest request) {
            return base.Channel.doReceiveSMSArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<doReceiveSMSArrayResponse> doReceiveSMSArrayAsync(string uUsername, string uPassword, long uLastRowID) {
            doReceiveSMSArrayRequest inValue = new doReceiveSMSArrayRequest();
            inValue.Body = new doReceiveSMSArrayRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            inValue.Body.uLastRowID = uLastRowID;
            return ((smsSoap)(this)).doReceiveSMSArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getInfoXMLResponse smsSoap.getInfoXML(getInfoXMLRequest request) {
            return base.Channel.getInfoXML(request);
        }
        
        public string getInfoXML(string uUsername, string uPassword) {
            getInfoXMLRequest inValue = new getInfoXMLRequest();
            inValue.Body = new getInfoXMLRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            getInfoXMLResponse retVal = ((smsSoap)(this)).getInfoXML(inValue);
            return retVal.Body.getInfoXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<getInfoXMLResponse> smsSoap.getInfoXMLAsync(getInfoXMLRequest request) {
            return base.Channel.getInfoXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<getInfoXMLResponse> getInfoXMLAsync(string uUsername, string uPassword) {
            getInfoXMLRequest inValue = new getInfoXMLRequest();
            inValue.Body = new getInfoXMLRequestBody();
            inValue.Body.uUsername = uUsername;
            inValue.Body.uPassword = uPassword;
            return ((smsSoap)(this)).getInfoXMLAsync(inValue);
        }
    }
}
